# Generated by Django 4.2.6 on 2023-11-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycleinfo',
            old_name='user',
            new_name='username',
        ),
    ]
