# Generated by Django 4.2.6 on 2023-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_user_cycleinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleinfo',
            name='phone_no',
            field=models.CharField(default='N/A', max_length=12),
        ),
    ]
