# Generated by Django 4.2.6 on 2023-11-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_booking_reviews_transactions_giving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giving',
            name='uniq',
            field=models.CharField(max_length=10),
        ),
    ]
