# Generated by Django 4.2.6 on 2023-11-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_giving_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='uniq',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
