# Generated by Django 4.2.6 on 2023-11-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_transactions_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='review1',
            field=models.FloatField(default=0),
        ),
    ]
