# Generated by Django 4.2.6 on 2023-11-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_transactions_cost_alter_transactions_review1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.CharField(max_length=10)),
                ('username1', models.CharField(max_length=40)),
                ('username2', models.CharField(max_length=40)),
                ('taken', models.BooleanField(default=False)),
                ('given', models.BooleanField(default=False)),
            ],
        ),
    ]
